### ISSUE TITLE
Review feedback from Maelle on this day

### ISSUE THREAD

**Issue by moodymudskipper** [moodymudskipper/devtag#1]
on Mattermost

In particular check how it plays out with pkgdown

If packagedown doesn't remove the files provide a wrapper that does remove them

**Comment by maelle** [comment]
So actually it does not play well with pkgdown if you use a reference config. https://github.com/igraph/rigraph/pull/1507

pkgdown doesn't ignore Rd files that Rbuildignored.
So maybe devtag should also add keywords internal? @moodymudskipper

**Comment by moodymudskipper** [comment]
This is clever!
Yes, and our draft PR looks good to me so far.

**Comment by maelle** [comment]
I'm improving it right now by seeing what fails in igraph :sweat_smile:
